defaults:
  - base_foundation
  - _self_

tile_threshold: 0.93
slide_max_threshold: 0.5
slide_mpm_threshold: 0.5
slide_top_k_threshold: 0.5
slide_span_threshold: 0.5 # arbitrary - span predictions are binary

checkpoint: "mlflow-artifacts:/61/fa2dd68895d14174a0eb3b0477aaf2f7/artifacts/checkpoints/epoch=0-step=11506/checkpoint.ckpt"
public_checkpoint: "..."

model_name: "PGP"
