defaults:
  - base_foundation
  - _self_

tile_threshold: 0.5
slide_threshold: 0.5

checkpoint: "mlflow-artifacts:/61/61e6c0a9808448089c3b04e50614a549/artifacts/checkpoints/epoch=4-step=2024/checkpoint.ckpt"
public_checkpoint: "..."

model_name: "Virchow2 (Hybrid-MIL)"
