# @package _global_

defaults:
  - /exploration/prostate/base
  - _self_

annot_table_path: "/mnt/data/MOU/prostate/slide_level_annotations/Prostaty2023-tabulka-final-corrections.xlsx"
data_dir: "/mnt/data/MOU/prostate/slide_level_annotations/slide_level_annotations"

metadata:
  run_name: MMCI 2k data
  description: MMCI 2k data
