# @package _global_

defaults:
  - /exploration/breast/base
  - _self_

original_metadata: "mlflow-artifacts:/61/59fec5d041064ed1b0a7552b663f19bf/artifacts/slides_with_folds.csv"

metadata:
  run_name: B20-24 Data
  description: B20-24 Data
