# @package _global_

output_path: ${carcinoma_artifacts}/manually_rescaled_slides/${data.data_name}/x${downsample_factor}
downsample_factor: ???
max_concurrent: 5
use_case: WSI resize

metadata:
  hyperparams:
    downsample_factor: ${downsample_factor}
