# @package _global_

output_path: ${carcinoma_artifacts}/${data.data_name}_rescaled/${desired_mpp}
desired_mpp: ???
max_concurrent: 5
use_case: WSI resize

metadata:
  hyperparams:
    desired_mpp: ${desired_mpp}
