# @package _global_

batch_size: 1024
output_path: ${carcinoma_artifacts}/tile_embeddings/${encoder_name}/${data.data_name}

encoder_name: ??? # logging purposes
tile_encoder:
  _target_: ???

uris: ???
use_case: Tile Embeddings ${tile_encoder}

metadata:
  hyperparams:
    model: ${encoder_name}
    batch_size: ${batch_size}
