defaults:
  - decode_head: embedding_classifier
  - backbone: virchow2
  - _self_

decode_head:
  in_features: 2560
  dropout: 0.0

_target_: ml.foundation_model.FoundationCarcinomaModel
lr: ???
tl_threshold: ???
