# @package _global_

defaults:
  - /exploration/colorectum/base
  - _self_

slides_dir: "/mnt/data/MOU/colorectum/colorectal_cancer_2020-2024-06"

metadata:
  run_name: C20-24 Data
  description: C20-24 Data
