defaults:
  - base_foundation
  - _self_

tile_threshold: 0.65
slide_threshold: 0.1796019971

checkpoint: "mlflow-artifacts:/65/9e9e6ec6817844c296004f0dc7369d1f/artifacts/checkpoints/epoch=6-step=1221/checkpoint.ckpt"
public_checkpoint: "mlflow-artifacts:/38/abde571304794242be0c1630b7bd16ce/artifacts/pgp_classic_mil_checkpoint.ckpt"

model_name: "PGP (Classic-MIL)"
