defaults:
  - base_foundation
  - _self_

tile_threshold: 0.77
slide_threshold: 0.1469607204

checkpoint: "mlflow-artifacts:/65/8613d45c98664f63b5cdd7e40e190986/artifacts/checkpoints/epoch=5-step=950/checkpoint.ckpt"
model_name: "Virchow2 (Classic-MIL)"
